//! `kora.lock` — what was actually resolved, and what its bytes were.
//!
//! A tag is what a human writes; a commit is what was used; a content hash is
//! what the bytes were. Recording all three is what stops a version number
//! coming to mean two different things over its lifetime. A maintainer who
//! force-pushes a tag, or a repository that is rewritten, changes the commit
//! or the hash — and a run checked against the lockfile refuses rather than
//! quietly executing something else.
//!
//! The file is generated, committed, and never hand-edited. Entries are
//! sorted, so a parallel resolve writes the same bytes as a serial one.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// One resolved git dependency.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Locked {
    /// Repository path, normalized: no scheme, no trailing `.git`.
    pub url: String,
    /// The reference as written, kept so a diff shows what a human asked for.
    pub reference: String,
    /// The commit that reference resolved to. This is the identity.
    pub commit: String,
    /// Hash of the checked-out tree, so tampering on disk is caught.
    pub hash: String,
}

impl Locked {
    /// Directory name under `.kora/deps`.
    ///
    /// The full repository path, so two packages with the same short name
    /// cannot collide, and the commit rather than the tag, so a moved tag
    /// gets its own directory instead of silently reusing the old bytes.
    /// `~` replaces path punctuation to keep it one directory level on every
    /// supported platform. A local Windows repository has both `:` and `\\`;
    /// leaving either intact could make its cache escape `.kora/deps`.
    pub fn slug(&self) -> String {
        let short = self.commit.chars().take(12).collect::<String>();
        format!("{}@{short}", self.url.replace(['/', '\\', ':'], "~"))
    }
}

/// The whole lockfile, keyed by repository.
#[derive(Debug, Clone, Default)]
pub struct Lock {
    packages: BTreeMap<String, Locked>,
}

impl Lock {
    pub const FILE: &'static str = "kora.lock";

    /// Read the lockfile beside a manifest. A missing one is empty, not an
    /// error: a project with no fetched dependencies has nothing to lock.
    pub fn at(root: &Path) -> Result<Lock, String> {
        let path = root.join(Lock::FILE);
        if !path.is_file() {
            return Ok(Lock::default());
        }
        let text = std::fs::read_to_string(&path)
            .map_err(|e| format!("cannot read {}: {e}", path.display()))?;
        Lock::parse(&text)
    }

    pub fn parse(text: &str) -> Result<Lock, String> {
        let root: toml::Value = text
            .parse()
            .map_err(|e| format!("kora.lock is not valid TOML: {e}"))?;
        let mut lock = Lock::default();
        let Some(entries) = root.get("package").and_then(|v| v.as_array()) else {
            return Ok(lock);
        };
        for entry in entries {
            let Some(table) = entry.as_table() else {
                continue;
            };
            let get = |key: &str| table.get(key).and_then(|v| v.as_str()).unwrap_or_default();
            let url = get("git").to_string();
            if url.is_empty() {
                continue;
            }
            lock.packages.insert(
                url.clone(),
                Locked {
                    url,
                    reference: get("ref").to_string(),
                    commit: get("commit").to_string(),
                    hash: get("hash").to_string(),
                },
            );
        }
        Ok(lock)
    }

    pub fn get(&self, url: &str) -> Option<&Locked> {
        self.packages.get(url)
    }

    pub fn insert(&mut self, locked: Locked) {
        self.packages.insert(locked.url.clone(), locked);
    }

    pub fn is_empty(&self) -> bool {
        self.packages.is_empty()
    }

    pub fn entries(&self) -> impl Iterator<Item = &Locked> {
        self.packages.values()
    }

    /// Render the file. Sorted by repository, so a parallel resolve and a
    /// serial one produce identical bytes and a diff shows only real changes.
    pub fn render(&self) -> String {
        let mut out = String::from(
            "# Generated by kora. Committed, and never hand-edited.\n\
             #\n\
             # `commit` is the identity: a tag can be moved, a commit cannot.\n\
             # `hash` is the content of the checked-out tree, verified on every run.\n",
        );
        for locked in self.packages.values() {
            out.push_str("\n[[package]]\n");
            out.push_str(&format!("git = {:?}\n", locked.url));
            out.push_str(&format!("ref = {:?}\n", locked.reference));
            out.push_str(&format!("commit = {:?}\n", locked.commit));
            out.push_str(&format!("hash = {:?}\n", locked.hash));
        }
        out
    }

    pub fn write(&self, root: &Path) -> Result<(), String> {
        let path = root.join(Lock::FILE);
        std::fs::write(&path, self.render())
            .map_err(|e| format!("cannot write {}: {e}", path.display()))
    }
}

/// Where fetched dependencies live.
///
/// Under `.kora/`, because it is tool-owned and reproducible from the
/// lockfile: one line in `.gitignore`, and never committed. Distinct from
/// `vendor/`, which is a deliberate, committed copy.
pub fn deps_dir(root: &Path) -> PathBuf {
    root.join(".kora").join("deps")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Locked {
        Locked {
            url: "github.com/org/receipts".to_string(),
            reference: "v0.3.1".to_string(),
            commit: "a1b2c3d4e5f60718".to_string(),
            hash: "sha256:deadbeef".to_string(),
        }
    }

    #[test]
    fn a_lockfile_round_trips() {
        let mut lock = Lock::default();
        lock.insert(sample());
        let parsed = Lock::parse(&lock.render()).unwrap();
        assert_eq!(parsed.get("github.com/org/receipts"), Some(&sample()));
    }

    #[test]
    fn a_missing_lockfile_is_empty_not_an_error() {
        assert!(Lock::parse("").unwrap().is_empty());
    }

    #[test]
    fn entries_are_sorted_so_the_bytes_do_not_depend_on_resolve_order() {
        let mut a = Lock::default();
        a.insert(sample());
        a.insert(Locked {
            url: "github.com/org/aaa".to_string(),
            ..sample()
        });

        let mut b = Lock::default();
        b.insert(Locked {
            url: "github.com/org/aaa".to_string(),
            ..sample()
        });
        b.insert(sample());

        assert_eq!(a.render(), b.render());
        assert!(a.render().find("aaa") < a.render().find("receipts"));
    }

    #[test]
    fn a_slug_carries_the_repository_and_the_commit() {
        // The full path, so two packages with the same short name cannot
        // collide; the commit, so a moved tag gets its own directory rather
        // than silently reusing the old bytes.
        assert_eq!(sample().slug(), "github.com~org~receipts@a1b2c3d4e5f6");
    }

    #[test]
    fn a_windows_path_stays_inside_the_dependency_store() {
        let local = Locked {
            url: r"C:\work\packages\receipts".to_string(),
            ..sample()
        };
        let slug = local.slug();
        assert_eq!(slug, "C~~work~packages~receipts@a1b2c3d4e5f6");
        assert!(!slug.contains(['/', '\\', ':']));
    }

    #[test]
    fn two_commits_of_one_repository_get_different_directories() {
        let old = sample();
        let new = Locked {
            commit: "ffffffffffffffff".to_string(),
            ..sample()
        };
        assert_ne!(old.slug(), new.slug());
    }
}
